version: 4
shared:
  template: java-platform/maven-open-jdk-8-rhel7@1.0.9
  settings:
    email: local-search-dev@verizonmedia.com
  steps:
    - preinit: export LANG=en_US.UTF-8

jobs:
  pull-request:
    requires: [~pr]
    steps:
      - presonar: |
          ls -al .
          ls -al ./target
          ls -al ./target/site
          ls -al ./target/site/clover

  component:
    requires: [~commit]

  release:
    requires: [component]

