platform: java

shared:
  notifications:
    email: localsearch-vespa-devel@yahoo-inc.com
  plugins:
    test_results:
      type: junit
      parameters:
        path: "**/target/surefire-reports/**"

jobs:
  release:
    order: [init, assemble, flatten, restore, maven-build, maven-release-prepare, maven-release-perform]
    